#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

die() { echo "Error: $*" >&2; exit 1; }
existing_value() {
  [[ -f .env ]] || return 0
  awk -F= -v key="$1" '$1 == key { value=$2 } END { print value }' .env
}
command -v arecord >/dev/null 2>&1 || die "arecord is missing. Run ./install.sh first."

echo ""
echo "Sona Speech Test Setup"
echo ""
echo "Detected recording devices:"
echo ""

mapfile -t CARDS < <(arecord -l 2>/dev/null | sed -nE 's/^card ([0-9]+): ([^ ]+) \[([^]]+)\].*/\1|\2|\3/p')
if ((${#CARDS[@]} == 0)); then
  echo "No ALSA recording cards were detected."
  echo "Connect the USB microphone, then run: ./sona-stt devices"
  exit 1
fi

for index in "${!CARDS[@]}"; do
  IFS='|' read -r card card_id description <<< "${CARDS[$index]}"
  printf '%d) %s\n' "$((index + 1))" "$description"
  printf '   ALSA hardware address: hw:%s,0\n' "$card"
  printf '   ALSA stable name: plughw:CARD=%s,DEV=0\n\n' "$card_id"
done
echo "0) Exit"
read -r -p "Select a microphone: " choice
[[ "$choice" =~ ^[0-9]+$ ]] || die "Please enter a number."
((choice == 0)) && exit 0
((choice >= 1 && choice <= ${#CARDS[@]})) || die "That selection is not available."

IFS='|' read -r _ card_id _ <<< "${CARDS[$((choice - 1))]}"
device="plughw:CARD=${card_id},DEV=0"
audio_gid="$(getent group audio | awk -F: '{print $3}')"
[[ -n "$audio_gid" ]] || die "Could not find the host audio group ID."
host_uid="$(id -u)"
host_gid="$(id -g)"
stt_model="$(existing_value STT_MODEL)"; stt_model="${stt_model:-tiny.en}"
stt_language="$(existing_value STT_LANGUAGE)"; stt_language="${stt_language:-en}"
record_seconds="$(existing_value STT_RECORD_SECONDS)"; record_seconds="${record_seconds:-5}"
wakeword_mode="$(existing_value WAKEWORD_MODE)"; wakeword_mode="${wakeword_mode:-preset}"
wakeword_preset="$(existing_value WAKEWORD_PRESET)"; wakeword_preset="${wakeword_preset:-hey jarvis}"
wakeword_custom_model="$(existing_value WAKEWORD_CUSTOM_MODEL)"
wakeword_threshold="$(existing_value WAKEWORD_THRESHOLD)"; wakeword_threshold="${wakeword_threshold:-0.5}"
stt_backend="$(existing_value STT_BACKEND)"; stt_backend="${stt_backend:-local}"
stt_remote_url="$(existing_value STT_REMOTE_URL)"
stt_remote_timeout="$(existing_value STT_REMOTE_TIMEOUT)"; stt_remote_timeout="${stt_remote_timeout:-180}"
groq_key="$(existing_value GROQ_API_KEY)"; cerebras_key="$(existing_value CEREBRAS_API_KEY)"; tavily_key="$(existing_value TAVILY_API_KEY)"
groq_stt_model="$(existing_value GROQ_STT_MODEL)"; groq_stt_model="${groq_stt_model:-whisper-large-v3-turbo}"
groq_tts_model="$(existing_value GROQ_TTS_MODEL)"; groq_tts_model="${groq_tts_model:-canopylabs/orpheus-v1-english}"
groq_tts_voice="$(existing_value GROQ_TTS_VOICE)"; groq_tts_voice="${groq_tts_voice:-autumn}"
tts_audio_device="$(existing_value TTS_AUDIO_DEVICE)"; cerebras_model="$(existing_value CEREBRAS_MODEL)"; cerebras_prompt="$(existing_value CEREBRAS_SYSTEM_PROMPT)"

# The bind-mounted directory must be writable by the non-root container user.
mkdir -p recordings
if [[ ! -w recordings ]]; then
  echo "Repairing ownership of recordings/ from an earlier Docker run..."
  sudo chown -R "${host_uid}:${host_gid}" recordings
fi

cat > .env <<EOF
# Generated by setup.sh. This file intentionally stays out of Git.
STT_AUDIO_DEVICE=${device}
STT_MODEL=${stt_model}
STT_LANGUAGE=${stt_language}
STT_RECORD_SECONDS=${record_seconds}
AUDIO_GID=${audio_gid}
STT_UID=${host_uid}
STT_GID=${host_gid}
STT_BACKEND=${stt_backend}
STT_REMOTE_URL=${stt_remote_url}
STT_REMOTE_TIMEOUT=${stt_remote_timeout}
GROQ_API_KEY=${groq_key}
GROQ_STT_MODEL=${groq_stt_model}
GROQ_TTS_MODEL=${groq_tts_model}
GROQ_TTS_VOICE=${groq_tts_voice}
TTS_AUDIO_DEVICE=${tts_audio_device}
CEREBRAS_API_KEY=${cerebras_key}
CEREBRAS_MODEL=${cerebras_model:-gpt-oss-120b}
CEREBRAS_SYSTEM_PROMPT=${cerebras_prompt}
TAVILY_API_KEY=${tavily_key}
WAKEWORD_MODE=${wakeword_mode}
WAKEWORD_PRESET=${wakeword_preset}
WAKEWORD_CUSTOM_MODEL=${wakeword_custom_model}
WAKEWORD_THRESHOLD=${wakeword_threshold}
EOF

echo ""
echo "Selected: $device"
echo "Saved microphone settings to .env"
echo ""
echo "Host USB devices:"
lsusb || true
