#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

die() { echo "Error: $*" >&2; exit 1; }
command -v arecord >/dev/null 2>&1 || die "arecord is missing. Run ./install.sh first."

echo ""
echo "Sona Speech Test Setup"
echo ""
echo "Detected recording devices:"
echo ""

mapfile -t CARDS < <(arecord -l 2>/dev/null | sed -nE 's/^card ([0-9]+): ([^ ]+) \[([^]]+)\].*/\1|\2|\3/p')
if ((${#CARDS[@]} == 0)); then
  echo "No ALSA recording cards were detected."
  echo "Connect the USB microphone, then run: ./sona-stt devices"
  exit 1
fi

for index in "${!CARDS[@]}"; do
  IFS='|' read -r card card_id description <<< "${CARDS[$index]}"
  printf '%d) %s\n' "$((index + 1))" "$description"
  printf '   ALSA hardware address: hw:%s,0\n' "$card"
  printf '   ALSA stable name: plughw:CARD=%s,DEV=0\n\n' "$card_id"
done
echo "0) Exit"
read -r -p "Select a microphone: " choice
[[ "$choice" =~ ^[0-9]+$ ]] || die "Please enter a number."
((choice == 0)) && exit 0
((choice >= 1 && choice <= ${#CARDS[@]})) || die "That selection is not available."

IFS='|' read -r _ card_id _ <<< "${CARDS[$((choice - 1))]}"
device="plughw:CARD=${card_id},DEV=0"
audio_gid="$(getent group audio | awk -F: '{print $3}')"
[[ -n "$audio_gid" ]] || die "Could not find the host audio group ID."

cat > .env <<EOF
# Generated by setup.sh. This file intentionally stays out of Git.
STT_AUDIO_DEVICE=${device}
STT_MODEL=${STT_MODEL:-tiny.en}
STT_LANGUAGE=${STT_LANGUAGE:-en}
STT_RECORD_SECONDS=${STT_RECORD_SECONDS:-5}
AUDIO_GID=${audio_gid}
EOF

echo ""
echo "Selected: $device"
echo "Saved microphone settings to .env"
echo ""
echo "Host USB devices:"
lsusb || true

